name: reachy-env

dependencies:
    - python=3.6
    - numpy
    - pandas
    - matplotlib
    - libopencv
    - opencv
    - py-opencv
    - tqdm
    - pip
    - jupyter
    - tensorflow
    - protobuf
    - pyaudio
    - swig
    - pip:
        - reachy==1.3.2
        - paho-mqtt
        - webrtcvad
        - pocketsphinx
        - respeaker
        - deepspeech
