name: reachy-docker

dependencies:
    - python=3.6
    - numpy
    - pandas
    - matplotlib
    - libopencv
    - opencv
    - py-opencv
    - tqdm
    - pip
    - jupyter
    - pip:
        - reachy==1.2.3
